---
# Absolute path to working directory
workdir_top: "/omics/groups/OE0219/internal/Valentin/JMML/amplicon/"
# Run specific configurations
threads: 4
STAR_reference: "/omics/groups/OE0219/internal/Valentin/genomes/hg38_ensembl/star/"

